### PR TITLE
Add /overview to print table containing information about runs/data

### PR DESCRIPTION
**Pull request by mboecker**

### CODE REVIEW

**Comment by mboecker** [comment]
```
MariaDB [openml_native]> select * from data_quality WHERE data = 3;
+------+----------------------------------------+----------------------+----------------------+-------------+
| data | quality                                | evaluation_engine_id | value                | description |
+------+----------------------------------------+----------------------+----------------------+-------------+
|    3 | AutoCorrelation                        |                    1 | 0.9990610328638497   | NULL        |
|    3 | Dimensionality                         |                    1 | 0.011576971214017523 | NULL        |
|    3 | MajorityClassPercentage                |                    1 | 52.221526908635795   | NULL        |
|    3 | MajorityClassSize                      |                    1 | 1669.0               | NULL        |
|    3 | MinorityClassPercentage                |                    1 | 47.778473091364205   | NULL        |
|    3 | MinorityClassSize                      |                    1 | 1527.0               | NULL        |
|    3 | NumberOfBinaryFeatures                 |                    1 | 35.0                 | NULL        |
|    3 | NumberOfClasses                        |                    1 | 2.0                  | NULL        |
|    3 | NumberOfFeatures                       |                    1 | 37.0                 | NULL        |
|    3 | NumberOfInstances                      |                    1 | 3196.0               | NULL        |
|    3 | NumberOfInstancesWithMissingValues     |                    1 | 0.0                  | NULL        |
|    3 | NumberOfMissingValues                  |                    1 | 0.0                  | NULL        |
|    3 | NumberOfNumericFeatures                |                    1 | 0.0                  | NULL        |
|    3 | NumberOfSymbolicFeatures               |                    1 | 37.0                 | NULL        |
|    3 | PercentageOfBinaryFeatures             |                    1 | 94.5945945945946     | NULL        |
|    3 | PercentageOfInstancesWithMissingValues |                    1 | 0.0                  | NULL        |
|    3 | PercentageOfMissingValues              |                    1 | 0.0                  | NULL        |
|    3 | PercentageOfNumericFeatures            |                    1 | 0.0                  | NULL        |
|    3 | PercentageOfSymbolicFeatures           |                    1 | 100.0                | NULL        |
+------+----------------------------------------+----------------------+----------------------+-------------+
```

Since the baseline itself isn't saved in the database where I can find it, I'm currently using 1 / number_of_classes for the baseline, but I think we need to compensate the size of the classes.

**Comment by jakob-r** [comment]
> Since all the tasks are binary-classification, we could use MajorityClassPercentage, can't we? 

Even for multiclass this would be a valid baseline

**Comment by jakob-r** [comment]
I simplified it a bit. But thinking about it I would prefer this calculation in the preparation. It should all be part of `save_task_metadata.R` and `task_metadata.Rds`.
Also I found some tasks that do not have metadata but runs in the database.

E.g.: data 1116 with task_id 3950 and 3950

**Comment by jakob-r** [comment]
I found some task_ids that do not have any metadata but runs. Can you investigate?

e.g. task_id: 3950

**Comment by mboecker** [comment]
> I found some task_ids that do not have any metadata but runs. Can you investigate?
> 
> e.g. task_id: 3950

first of all, task id 3950 isn't listed in this paper [1].
Do we still need that task then?

[1]: https://arxiv.org/pdf/1806.10961.pdf

**Comment by mboecker** [comment]
> > I found some task_ids that do not have any metadata but runs. Can you investigate?
> > e.g. task_id: 3950
> 
> first of all, task id 3950 isn't listed in this paper [1](https://arxiv.org/pdf/1806.10961.pdf).
> Do we still need that task then?

this was caused by "inner merging" only, which caused tasks, which don't have a run with every algorithm to be removed. I fixed this and now the table displays 0 instead.

**Pull request merged**
